GET http://localhost:3000/articles

### 
GET http://localhost:3000/articles/drafts

###
GET http://localhost:3000/articles/clppqz2ia0001109axf9nq3sj

###
POST http://localhost:3000/articles
Content-Type: application/json

{
    "title": "O Melhor Anime do Mundoooo!",
    "description": "Naruto",
    "body": "Anime que marcou a infância de muitas crianças."
}

###
PATCH http://localhost:3000/articles/clppqz2ia0001109axf9nq3sj
Content-Type: application/json

{
    "title": "Java não é Javascript."
}