GET http://localhost:3000/articles

### 
GET http://localhost:3000/articles/drafts

###
GET http://localhost:3000/articles/clppqz2ia0001109axf9nq3sj

###
POST http://localhost:3000/articles
Content-Type: application/json

{
  "title": "example-title1222",
  "description": "example-description",
  "body": "example-body",
  "published": true
}

###
PATCH http://localhost:3000/articles/clppqz2ia0001109axf9nq3sj
Content-Type: application/json

{
    "title": "Java não é Javascript."
}

###
DELETE http://localhost:3000/articles/clppqz2hm0000109aa2yerz5s