GET http://localhost:3000/users

### 
GET http://localhost:3000/users/clprlft00000014c90wqp83cy

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "bruno",
  "email": "bruno@gmail.com",
  "password": "example-body"
}

###
PATCH http://localhost:3000/users/clprl9m200001vypizbhix4nr
Content-Type: application/json

{
    "name": "John Doe"
}

###
DELETE http://localhost:3000/users/clprl9m200001vypizbhix4nr