GET http://localhost:3000/articles

### 
GET http://localhost:3000/articles/drafts

###
GET http://localhost:3000/articles/clprmteiw000584vds0b9zrpz

###
POST http://localhost:3000/articles
Content-Type: application/json

{
  "title": "example-title1222",
  "description": "example-description",
  "body": "example-body",
  "published": true
}

###
PATCH http://localhost:3000/articles/5757845
Content-Type: application/json

{
    "title": "Java não é Javascript."
}

###
DELETE http://localhost:3000/articles/5757845